### ISSUE TITLE
Pointer creation failure

### ISSUE THREAD

**Issue by geeksnglitter** [brianjgeiger/osf.io#103]
When you try to create a new pointer, if you pass an incorrect node_id, the api will give a 500 response instead of the expected 404, 405 or so.

**Comment by geeksnglitter** [comment]
@brianjgeiger did you magically fix this in the last hour? I am having trouble recreating.

**Comment by brianjgeiger** [comment]
Interesting. I had made some modifications which were merged in sometime since lunch, but yay for inconsistent errors. :/

**Comment by brianjgeiger** [comment]
If you can see if there's some sort of pattern, that would be great.

**Comment by geeksnglitter** [comment]
These errors only occur when you **have access** to the first pk you enter. If you do not have access, it knows to send a 403.
1.So, when you put in a real pk, but a fake node - it send a 500 only if you had access to the first pk.
2.If you try to connect a node to itself - 500.
3.When you do not have access to the second node - 500. ~Somewhat inconsistent
4.When nodes are already connected -500 ~Somewhat inconsistent.

**Comment by brianjgeiger** [comment]
Moved to main repo
