### ISSUE TITLE
Upload file url requires mid string editing to work

### ISSUE THREAD

**Issue by alexschiller** [brianjgeiger/osf.io#106]
1. File upload via url currently requires adding file name to the middle of the url string (see image)
2. File self link lists access is via POST it is supposed to be PUT (see here: https://staging2.osf.io/api/v2/nodes/4s8q3/files/

![screen shot 2015-06-05 at 4 09 53 pm](https://cloud.githubusercontent.com/assets/1322421/8014318/ba44350a-0b9d-11e5-962f-349fb12a81f2.png)

Example code for upload currently (note the bolded matched text for emphasis)
f = open('/Users/alexanderschiller/Desktop/<b>stupid.txt</b>', 'rb')
r = requests.put("https://files-api-staging2.osf.io/file?path=%2F<b>stupid.txt</b>&nid=4s8q3&provider=osfstorage&cookie=5571f2f6404f77020c09dcbf.ve8ATKGiyIYI9dc3kaLA89cV8wM", f.read())

---
Could be fixed by having file added at the end or writing a wrapper to make it more accessible.

**Comment by brianjgeiger** [comment]
Moved to main repo.
