### ISSUE TITLE
Update all tests to use URLs relative to API_BASE

### ISSUE THREAD

**Issue by abought** [brianjgeiger/osf.io#109]
All API unit tests currently point to URLs of the form `v2/<endpoint>`, which is a form of hard-coding and could break if the URL prefix in Django ever changes.

These URLs should be modified to add the prefix based on `osf.io/api/base/settings/defaults.py: API_BASE`. 

This would affect anything that lives under `tests/api_tests`.

**Comment by brianjgeiger** [comment]
Moved to main repo
