### ISSUE TITLE
Configure caching

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#23]
Get the back-end DRF caching working

**Comment by samanehsan** [comment]
This is required for #22, so I will look into this as well.

**Comment by sloria** [comment]
Can you clarify the scope of this issue? I'm not clear on what is meant by caching.

**Comment by brianjgeiger** [comment]
@sloria, this was a thing you requested and @samanehsan implemented, so I'll let you to chat about it.

**Comment by sloria** [comment]
I originally requested looking into API rate limiting.

**Comment by samanehsan** [comment]
In order for API rate limiting to work, we need to configure the cache settings: http://www.django-rest-framework.org/api-guide/throttling/#setting-up-the-cache. The default local memory caching backend is not recommended for production, so I used memcached instead.

**Comment by brianjgeiger** [comment]
Rolling this into the rate limiting issue.
