### ISSUE TITLE
Node contributors

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#24]
Contributors to a node should be broken up into bibliographic and non-bibliographic contributors.

```json
data: {
    bibliographic: [],
    non-bibliographic: []
}
```

**Comment by samanehsan** [comment]
Just the counts or the links as well?

**Comment by brianjgeiger** [comment]
As discussed in person, let's have a link for bibliographic contributors and a link for non-bibliographic contributors. These will each return lists of users, rather than the complicated thing I described above.
