### ISSUE TITLE
Swagger documentation modifications

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#27]
Currently, the Swagger documentation is being generated from the DRF and served with the plugin that created the documentation. There are currently two issues with this. The smaller issue is that the static files for the docs only show if you are running through the main OSF app, and not while solely on the DRF app (port 8000). 

However, the Django-Rest-Swagger project itself is a little behind the times (using Swagger spec 1.2 and not 2.0), and I'm having philosophical doubts as to whether we should link the documentation directly to the implementation. I think the proper thing to do, though it'll be more work, is to generate the docs by hand serve them through the standard Swagger API (though with modifications to make it look the way we want per #15).

**Comment by sloria** [comment]
Former issue probably has to do with this setting: https://github.com/CenterForOpenScience/osf.io/blob/4a18effa8162646ba5dc228c8bb7a673882cad76/api/base/settings.py#L103 , which allows the browseable API to work on `/api/v2/` . When we make the API public facing, we'll probably remove that setting (`/api/v2/`) is for internal use only.

At least for initial iterations, I don't think we'll want to manually maintain a swagger spec and serve the swagger UI on a separate server. The benefits of using swagger 2.0 vs. 1.2 don't seem to outweigh the maintenance cost and risk for "doc rot" (I would rather see developer resources dedicated to addressing https://github.com/marcgibbons/django-rest-swagger/issues/250 if we really wanted to use swagger 2.0).
