### ISSUE TITLE
Node files tests

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#39]

**Comment by HarryRybacki** [comment]
Willing to help jump on these, for whoever wrote the files views, did you come up with a list of edge cases or anything I can get kickstarted with?

**Comment by samanehsan** [comment]
@HarryRybacki, I'm actually taking a look at these right now -- just forgot to assign myself!

**Comment by HarryRybacki** [comment]
@samanehsan excellent
