### ISSUE TITLE
Refactor ListFilterMixin

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#42]
We need a couple of changes to the ListFilterMixin to make it more generalizable and to address a couple concerns from the code review. Essentially, I think we want to:

1. Move https://github.com/brianjgeiger/osf.io/blob/feature/api-v2-drf/api/base/filters.py#L155-L161 from the param_queryset method into the get_serializer_field_value method. 
2. We should probably determine how to do comparisons a little more like https://github.com/brianjgeiger/osf.io/blob/feature/api-v2-drf/api/base/filters.py#L81-L92 rather than a series of if statements (if we can). 
3. Finally, we need to generalize how we are getting the serializer function for serializerMethodField based fields. Fortunately, we know that the way to get the value for that is that the method name will have to be `get_fieldname` for any arbitrary `fieldname`, so we can construct that into a string and use getattr to call it as needed. http://stackoverflow.com/questions/3061/calling-a-function-of-a-module-from-a-string-with-the-functions-name-in-python

@samanehsan, do you want to do this refactor or would you like me to? Item 2 may or may not make sense as we aren't doing db queries, but I think 1 will help readability a bit and 3 will keep us from having to write custom code for every method field we use.

**Comment by samanehsan** [comment]
@brianjgeiger, I can do the refactor if you haven't already started

**Comment by brianjgeiger** [comment]
I have not; go for it.
