### ISSUE TITLE
Filtering for 'me' overly aggressive

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#47]
Steps
--------
1. Find out your user id
2. Create a project with your user id as the title
3. go to the api endpoing nodes/filter[title]=me

Expected
-------------
The new project you created would not be returned (unless your user id contains the characters 'me' in that order somehow)

Actual
---------
The filter shows that project

Here's the problem: https://github.com/brianjgeiger/osf.io/blob/feature/api-v2-drf/api/base/filters.py#L65-L67

First, create a filter test to check for that case (being sure that the user id you create can't have 'me' in it anywhere. Then fix the problem.

**Comment by brianjgeiger** [comment]
![screen shot 2015-05-11 at 4 10 30 pm](https://cloud.githubusercontent.com/assets/6599111/7574203/87553db8-f7f9-11e4-8c3d-41c4fe1f16d6.png)

**Comment by brianjgeiger** [comment]
Oh, and the purpose of the 'me' value is to ensure that if you go to /users/me it takes you to your user detail as if you wen to /users/{your user id}. We might not need it for filtering, we may just want to use the shortcut for REST paths.

**Comment by brianjgeiger** [comment]
I am doing the bare minimum on this, removing the filter elif that subs out the 'me'. I'll leave the rest for you, @HarryRybacki.

**Comment by brianjgeiger** [comment]
@HarryRybacki I do not have a timeframe of when I need this, but I am curious if you know yet when you might be able to work on it.

**Comment by HarryRybacki** [comment]
@brianjgeiger -- I'll probably polish off the remainder of today/tomorrow with updating the Retraction/Embargo PR with the CR Steve finished last night. After that it all depends on if this feature is going to be put in this epic or pushed (which will depend on how QA receives it). tl;dr I don't have a good answer yet =/
