### ISSUE TITLE
Django rest swagger only partially detects root endpoint

### ISSUE THREAD

**Issue by samanehsan** [brianjgeiger/osf.io#55]
Django rest swagger includes an unnamed row with the actions "Show/hide", "expand operations", etc. It applies to all of the routes, but it doesn't seem entirely functional. For example, "show/hide" will list all routes, but will not hide them and "list operations" will not return the expanded operations back to a list. 

![screen shot 2015-05-12 at 9 50 41 am](https://cloud.githubusercontent.com/assets/6414394/7594298/9c81bef0-f8ad-11e4-81af-7282958e5f2d.png)

It seems like this should actually be the root endpoint, because changing the root endpoint to something other than "/" will give you this:  
![screen shot 2015-05-12 at 1 33 49 pm](https://cloud.githubusercontent.com/assets/6414394/7594317/b8aaa830-f8ad-11e4-820f-9a47b7a9e1e4.png)

Leaving this open to discussion about how we want to include the root route in django rest swagger. This is a simple solution, but there might be others.

**Comment by samanehsan** [comment]
Adding this to the release milestone so we don't forget about it!

**Comment by brianjgeiger** [comment]
Fixed
