### ISSUE TITLE
NodeDetail endpoint update operation fails with KeyError

### ISSUE THREAD

**Issue by abought** [brianjgeiger/osf.io#61]
The NodeDetail view (sample url `http://127.0.0.1:5000/api/v2/nodes/<node_id>` ) currently does not accept update/patch operations. Sending a patch request to an existing node returns a KeyError in Django.

## First cause
Primarily, this fails because the `update` view [expects a JSON key `is_public`](https://github.com/brianjgeiger/osf.io/blob/838ea28452cb49cb935e1722cd3e89a093f048f4/api/nodes/serializers.py#L104) , but the serialized field in the request body [goes by the name `public`](https://github.com/brianjgeiger/osf.io/blob/838ea28452cb49cb935e1722cd3e89a093f048f4/api/nodes/serializers.py#L52).

## Further causes
A secondary cause of the update failure is that the `validated_data` dictionary passed to the serializer `update` method is empty. (an empty dictionary won't have a key named `public` regardless) The PATCH request would return 200 OK if the KeyError was fixed, but the instance would still not be changed upon submitting the "update".

The failure to update is currently under investigation.

## Suggestions
Unit tests are needed that cover node create and delete operations via the API.

**Comment by brianjgeiger** [comment]
I've added tests for PUT and POST, and those work consistently. I'll try PATCH next.

**Comment by brianjgeiger** [comment]
Yup. Replicated the PATCH problem. Let's see what's happening there.

**Comment by brianjgeiger** [comment]
What was happening is that the update function in the serializer wasn't checking for if public were being set in a partial update before trying to validate, at least for the problems I was having with my tests (Fixed in 2ea2bd58a8dddd653565f2082fb97728b0c0127c) . I haven't quite figured out how to properly set the description to something not descriptiony yet. Getting a JSON Parse error.

**Comment by brianjgeiger** [comment]
Okay, to clear the description, you set it to "" rather than null. The JSON error is because the Django docs are a little persnickity about the format of the JSON. It wants to remove the whitespace inside the braces. As near as I can tell, this works properly.

**Comment by abought** [comment]
This seems to work for clearing the description- but existing instances can be created via other means that will have a `null` description.

This leads to a small edge case where the API can fail in a patch request when trying to modify existing valid instances. Separate issue, perhaps...

**Comment by brianjgeiger** [comment]
Fixed in de3d869d8ebf502872143317d00087807e9e6c62
