### ISSUE TITLE
Permission coverage for tests

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#69]
We need to go through all of the tests for the API and verify that each of them cover, as appropriate, accessing every endpoint with every method:

1) While not logged in for public resource
2) While not logged in for a private resource
3) While logged in for a public resource
4) While logged in for a private resource that you have access to
5) While logged in for a private resource that you do not have access to

**Comment by pattisdr** [comment]
- [X] Review API node tests and document permission coverage
- [  ] Fill in gaps for permission coverage

**Comment by brianjgeiger** [comment]
Fantastic, thank you for the task list. :+1:
