### ISSUE TITLE
throbber.gif not found 

### ISSUE THREAD

**Issue by samanehsan** [brianjgeiger/osf.io#71]
Steps: 
1) Go to localhost:8000/v2/docs
2) Expand an endpoint (like /v2/nodes) 
3) Click "Try it out"

One of those broken image pictures flashes on the page where the throbber.gif should be. Also, if you check the js console, there is a 404 error when trying to GET that resource: 

![screen shot 2015-05-20 at 11 05 49 am](https://cloud.githubusercontent.com/assets/6414394/7729139/2563db7a-fee1-11e4-837c-9e3637db8a0d.png)

**Comment by brianjgeiger** [comment]
Looks like it's not adding the static path in.

**Comment by samanehsan** [comment]
Yeah, it's supposed to be `static` instead of `docs`

**Comment by brianjgeiger** [comment]
Which is odd, because it looks like it should be:

```html
<img alt='Throbber' class='response_throbber' src='"+ window.static_url +"rest_framework_swagger/images/throbber.gif' style='display:none' />
```

**Comment by brianjgeiger** [comment]
unless, of course, window.static_url isn't defined.

**Comment by brianjgeiger** [comment]
base.html should be defining that. Does this look right, or should it be {{static}} instead (or something else)?

```html
        <script>
            window.static_url = '{{STATIC_URL}}';
        </script>
````

**Comment by samanehsan** [comment]
I logged window.static_url to the console and it's nothing...an empty string maybe?

**Comment by samanehsan** [comment]
That does look right. I actually didn't change base.html, it's just versioned because it's a part of their latest development version and not the one we pip installed.

**Comment by brianjgeiger** [comment]
Got it.

```html
        <script>
            window.static_url = "{% static '' %}";
        </script>
````

**Comment by brianjgeiger** [comment]
Fixed in 2f92d72097aff0e4803f18bae0d4e1f58f89193b

**Comment by samanehsan** [comment]
Nice!! :tada:

**Comment by brianjgeiger** [comment]
:tada: :penguin: :tada:
