### ISSUE TITLE
Create registrations with API

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#76]
This one is a little different from other create views. We want to enforce a confirmation capability with registrations to ensure that people understand the consequences of creating a registration. So I think it should work something like:

POST /v2/nodes/{pk}/registrations/
{ "public": true }

will result in an error that will give a confirmation message intending to be displayed and a token (and likely a self link) that will indicate that the user has acknowledged the confirmation message in some manner. Then the API client will:

POST /v2/nodes/{pk}/registrations/{token}
{ "public": true }

which will create the registration. The API client will not be able to do a single post in order to create a registration. This pattern will be reused. It should maintain RESTfulness because the route to post is different from the original route. We should require the public information (and the rest of the registration information including the type, embargo date, etc) in the original post as well as the follow-up so that we can give the appropriate message to the user (for example, that public registrations can't be made private).

**Comment by pattisdr** [comment]
Steps:
- [X]  Allow user to create bare bones registration through API (no registration supplement information or confirmation)
- [ ] Require registration supplement fields for original POST request 
- [ ] Validate that registration POST request has all required fields 
- [ ] Write a hash function to generate token to tack onto end of second POST request
- [ ] Change POST /v2/nodes/{pk}/registrations response to error.  Have user confirm they want to register project by submitting second post request, POST /v2/nodes/{pk}/registrations/{token}

**Comment by brianjgeiger** [comment]
Moved to main repo.
