### ISSUE TITLE
API does not sanitize inputs; arbitrary code injection possible 

### ISSUE THREAD

**Issue by abought** [brianjgeiger/osf.io#79]
## Summary

The API does not sanitize inputs; consequently, it is possible for an API user to inject arbitrary code or characters into input fields that would have been sanitized had they gone through the UI.

This bug allows arbitrary JavaScript code injection in some template fields, which is a severe security issue if this were to be released to production.

## Steps to reproduce
1. Enter the following string into the "description" field for a node (eg project) from the osf.io web page:
`<script>alert('My name is princess sparkle-pony!')</script>`
2. Hit enter. When the page reloads, the OSF front-end views we currently use should have stripped out the HTML. The description field should now read:
`alert('My name is princess sparkle-pony!')`

3. Go to the API edit endpoint for a "Node" in Django Rest Framework, eg a link of the form `localhost:8000/v2/nodes/2x3r5/`. Using the "raw data" field at bottom, edit the description field as shown and submit a PATCH request. (you may have to remove the outer `{data: }` that wraps the request body, otherwise changes will not be submitted)
![screen shot 2015-05-22 at 11 39 17 am](https://cloud.githubusercontent.com/assets/2957073/7774191/6f456aaa-0077-11e5-930d-1e646e922ba3.png)

4. Navigate back to the same OSF project page used earlier (eg `http://localhost:5000/2x3r5/`). A javascript dialog box will pop up, indicating that the script tags are being executed.
![screen shot 2015-05-22 at 11 15 33 am](https://cloud.githubusercontent.com/assets/2957073/7774196/763dd680-0077-11e5-84dc-93ea8779df5b.png)

## Expected behavior
The API v2 endpoints would perform the same input sanitization that the current front-end UI does.

## Actual Behavior
I am Princess Sparkle-Pony.

(which is to say that malicious input is rendered directly as provided)

Oddly, with the input as written above, I am also unable to edit the description field from the UI on the affected node. The option to click and edit description is simply not provided.

## Recommended fixes
Two-fold:
1. Sanitize all user-entered fields at API update and create endpoints
2. Implement markup safe rendering in Mako by default. (This will be a nasty QA task, but would mitigate bad inputs from actively harming users)

## References
Possibly related to centerforopenscience/osf.io/issues/946

**Comment by abought** [comment]
Added some fairly braindead sanitization to my working branch, for the OAuth2Application endpoints. Would be fairly straightforward to add this (or an improved version) to other classes as well.

https://github.com/abought/osf.io/commit/93f8281fe7663207f9965c55e0915fc145068cdf#diff-4bd3e0861a11a2b856682206b4ecea42R118

For reference, `strip_html` is what's currently used by current endpoint views, eg `project.views.node.edit_node`.

**Comment by brianjgeiger** [comment]
It's weird that that's not a field option in DRF, but that looks good. Could you make a separate PR for the other serializers so I can add it in before it gets merged into Develop?

**Comment by brianjgeiger** [comment]
And some tests as well, please.

**Comment by abought** [comment]
Will do. Admittedly, my investigation of DRF sanitizing options was fairly cursory; let me know if there's a smarter way.

Based on initial look at models, plan A is to attach the modified `is_valid` directly to `JSONAPISerializer` (the common parent). I don't think we have any fields that expect/ should allow HTML tags, in which case not much need for special casing. I'll run tests to be sure.

**Comment by brianjgeiger** [comment]
No, I think that's the proper way, I just think it's weird.

If you attach it directly to the JSONAPISerializer, then we have to have a way to turn it off if need be. I don't know of any reason we need to edit HTML right now, but if we changed how we were doing wikis, or if we were more hands-on with files, then we might need to.

**Comment by abought** [comment]
For now I'll go with this (plus a `clean_html=True` kwarg that can be used to suppress cleaning for all fields in a particular child serializer). 

If we need more control in the future, we could switch over and use some `to_internal_value` trickery in conjunction with a custom field type ("RawHTMLStringField" or somesuch). For now that may be overengineering.

**Comment by brianjgeiger** [comment]
Cool

**Comment by abought** [comment]
Addendum: here's an even better description field to use as a test case. (I find people like something visual)

```
        "description": "<script type=\"text/javascript\" src=\"http://www.cornify.com/js/cornify.js\"></script><script type=\"text/javascript\">cornify_add()</script>",
```

**Comment by abought** [comment]
PR merged; do we need additional testing before closing this ticket?

**Comment by brianjgeiger** [comment]
No, this should be good for our purposes right now.
