### ISSUE TITLE
API node update endpoint grants elevated permissions to users

### ISSUE THREAD

**Issue by abought** [brianjgeiger/osf.io#82]
## Summary

To a limited extent, the API makes it possible to circumvent normal access restrictions, and let users with limited permissions modify a project 

## Steps to reproduce

1. As `User A`, create an OSF project, with visibility set to "private" (the default)
2. Go to the Sharing tab and give Read+Write permissions to `User B`.
3. **In a separate browser (new session)**, log in as User B. Confirm that you can reach the OSF page for the project, but do not have the option to make the project public.
4. As User B, visit the API page for the newly created node (URL of the form `http://localhost:8000/v2/nodes/<project_id>/`)
5. Confirm that data can be seen.
6. Using the DRF web view,at the bottom of the page, change "public" from `false` to `true`. 
7. Use the DRF to send a `PATCH` request. (Make sure to remove the `{data: }` wrapping the request body)
8. As User A, refresh the project page. The toggle should now appear as public.

## Expected result

The API would enforce fine-grained permissions consistent with the current front-end behavior

## Actual result

The API allows users to modify a project in ways they normally could not.

Here is the view as Sam Pull, a Read+Write contributor. Note the lack of visibility toggle + log entry saying he made the change.
![screen shot 2015-05-23 at 9 59 19 pm](https://cloud.githubusercontent.com/assets/2957073/7786371/04ffef3c-0197-11e5-86c0-6d5d8a8b23df.png)

## Further work

Further investigation is needed to determine how far permissions escalation could go. (eg can read-only users also make a project public?) At the moment I'm having some issues with caching that make this difficult to test. (The DRF does not seem to be immediately reflecting when I log out of the OSF, or use the front-end to change an instance)

**Comment by brianjgeiger** [comment]
I think we should consider disabling any admin-level functionality from the API for the moment.

Also, test driven debugging would be super-handy in this instance.

**Comment by abought** [comment]
Per @brianjgeiger , these tests might be coordinated with #69 . I'll get to this Mon-Tues if no one else has yet.

**Comment by brianjgeiger** [comment]
Okay, I've made public read_only as of 2c99d61f9bb2322e1717eec4ea1d1322177e3410 and @pattisdr is revising tests to make sure that all works properly here.
