### ISSUE TITLE
Make URL helper functions to make it easy to go between Dev and Staging/Production

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#90]
Getting the base url/route for the API is a little weird right now because we are running as a separate service on development but it's pretending like it's integrated into the OSF in staging and production. So we need helper functions (probably one in JS and another in Python) to make it seamless for developers who need to use the OSF. The helper functions can grab the base url and route and construct an API based on the given route and the query parameters. This should *not* be a recreation of url_for; the API routes are still canonical, it's just that the starting point is different.

So, for example, 
```py
api_v2_url('/nodes/{}/contributors/'.format(node_id), 
            query_params=[{'filter[fullname]': 'bob'}, {'filter[fullname]': 'smith'}]) 
```
Would return `http://localhost:8000/v2/nodes/ezcuj/?filter[fullname]=bob&filter[fullname]=smith` on dev and `https://staging2.osf.io/api/v2/nodes/ezcuj/?filter[fullname]=bob&filter[fullname]=smith` on staging and `https://osf.io/api/v2/nodes/ezcuj/?filter[fullname]=bob&filter[fullname]=smith` on production. There should be a similar function in javascript that works the exact same way with the same calling structure (or as close as you can get and still make it look like javascript and work properly)

```js
apiV2Url(etc, etc);
```

**Comment by brianjgeiger** [comment]
There are settings variables for base url and the base path, so those are what you'd need to use for this.

**Comment by brianjgeiger** [comment]
Oh, also: the JS version of this should do CORS headers when appropriate and not do them if they aren't.

**Comment by abought** [comment]
The PR for this will be sent to the 0.38 branch; this is a reminder to check for regressions in case that branch is not fully merged after the dust settles.

**Comment by abought** [comment]
Updated PR for #2895; at this point perhaps it's better to send that to a different branch, though?

I'll make a separate issue for the CORS JS helpers.
