### ISSUE TITLE
Ensure an empty osf_settings.API_PORT works properly

### ISSUE THREAD

**Issue by brianjgeiger** [brianjgeiger/osf.io#91]
Currently, the API Port property is expecting a number. I expect that if it's empty, rather than going to the default port, it will append a : to the end of the URL with no port after it.

**Comment by abought** [comment]
Furl or urlparse should be able to deal with this intelligently..?

```
>>> e = furl.furl('http://google.com'); e.port=None; print str(e) 
http://google.com
```

**Comment by brianjgeiger** [comment]
:+1:

**Comment by brianjgeiger** [comment]
The setting is removed and unnecessary now.
